In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [6]:
data_path = Path("../data/raw/marketing_campaign.csv")

In [7]:
data_path.exists()

True

In [8]:
df = pd.read_csv(data_path, sep="\t")

In [9]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [10]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 50000
Number of columns: 29

In [11]:
df.columns.tolist()

['ID',
 'Year_Birth',
 'Education',
 'Marital_Status',
 'Income',
 'Kidhome',
 'Teenhome',
 'Dt_Customer',
 'Recency',
 'MntWines',
 'MntFruits',
 'MntMeatProducts',
 'MntFishProducts',
 'MntSweetProducts',
 'MntGoldProds',
 'NumDealsPurchases',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'Complain',
 'Z_CostContact',
 'Z_Revenue',
 'Response']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   Year_Birth           50000 non-null  int64
 2   Education            50000 non-null  str
 3   Marital_Status       50000 non-null  str
 4   Income               49976 non-null  float64
 5   Kidhome              50000 non-null  int64
 6   Teenhome             50000 non-null  int64
 7   Dt_Customer          50000 non-null  str
 8   Recency              50000 non-null  int64
 9   MntWines             50000 non-null  int64
 10  MntFruits            50000 non-null  int64
 11  MntMeatProducts      50000 non-null  int64
 12  MntFishProducts      50000 non-null  int64
 13  MntSweetProducts     50000 non-null  int64
 14  MntGoldProds         50000 non-null  int64
 15  NumDealsPurchases    50000 non-null  int64
 16  NumWebPurchases      50000 non-null  int64
 17  NumCatalogPurchases  50000 non-null  int64
 18  NumStorePurchases    50000 non-null  int64
 19  NumWebVisitsMonth    50000 non-null  int64
 20  AcceptedCmp3         50000 non-null  int64
 21  AcceptedCmp4         50000 non-null  int64
 22  AcceptedCmp5         50000 non-null  int64
 23  AcceptedCmp1         50000 non-null  int64
 24  AcceptedCmp2         50000 non-null  int64
 25  Complain             50000 non-null  int64
 26  Z_CostContact        50000 non-null  int64
 27  Z_Revenue            50000 non-null  int64
 28  Response             50000 non-null  int64
dtypes: float64(1), int64(25), str(3)
memory usage: 11.1 MB

In [13]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,50000.000000,50000.00000,49976.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,...,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.0,50000.0,50000.000000
mean,33750.825560,1968.83358,52429.576047,0.441520,0.504900,49.233740,305.365560,26.659680,168.47650,37.813120,...,5.296180,0.07168,0.074900,0.071720,0.063820,0.013480,0.009280,3.0,11.0,0.147880
std,14806.546977,11.75382,25934.660560,0.538763,0.543196,29.012183,338.483378,40.449643,227.69333,55.155891,...,3.314537,0.25796,0.263233,0.258026,0.244434,0.115319,0.095886,0.0,0.0,0.354985
min,0.000000,1893.00000,1641.049500,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,21451.750000,1959.00000,35463.165605,0.000000,0.000000,24.000000,24.000000,1.000000,16.00000,3.000000,...,3.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,33951.500000,1970.00000,51615.901476,0.000000,0.000000,50.000000,177.000000,8.000000,66.00000,12.000000,...,5.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,46451.250000,1977.00000,68365.788107,1.000000,1.000000,74.000000,503.000000,33.000000,234.00000,50.000000,...,7.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,58951.000000,1996.00000,721309.167447,2.000000,2.000000,99.000000,1679.000000,231.000000,2021.00000,291.000000,...,30.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [16]:
df.select_dtypes(include="object").nunique()

C:\Users\sanje\AppData\Local\Temp\ipykernel_12172\251659734.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").nunique()

Education           5
Marital_Status      8
Dt_Customer       663
dtype: int64

In [17]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].value_counts())

C:\Users\sanje\AppData\Local\Temp\ipykernel_12172\2182031402.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

 Education
Education
Graduation    25162
PhD           10800
Master         8351
2n Cycle       4507
Basic          1180
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     19546
Together    12779
Single      10611
Divorced     5187
Widow        1728
Alone          68
Absurd         42
YOLO           39
Name: count, dtype: int64

 Dt_Customer
Dt_Customer
22-05-2014    253
31-08-2012    251
14-02-2013    248
12-09-2012    246
12-05-2014    229
             ...
18-11-2013     15
31-01-2014     15
19-09-2012     15
04-02-2014     14
14-06-2014     14
Name: count, Length: 663, dtype: int64