In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [4]:
data_path = Path("../data/raw/marketing_campaign.csv")

In [5]:
df = pd.read_csv(data_path, sep="\t")

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 50000
Columns: 29

In [7]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [8]:
df.columns.tolist()

['ID',
 'Year_Birth',
 'Education',
 'Marital_Status',
 'Income',
 'Kidhome',
 'Teenhome',
 'Dt_Customer',
 'Recency',
 'MntWines',
 'MntFruits',
 'MntMeatProducts',
 'MntFishProducts',
 'MntSweetProducts',
 'MntGoldProds',
 'NumDealsPurchases',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'Complain',
 'Z_CostContact',
 'Z_Revenue',
 'Response']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   Year_Birth           50000 non-null  int64
 2   Education            50000 non-null  str
 3   Marital_Status       50000 non-null  str
 4   Income               49976 non-null  float64
 5   Kidhome              50000 non-null  int64
 6   Teenhome             50000 non-null  int64
 7   Dt_Customer          50000 non-null  str
 8   Recency              50000 non-null  int64
 9   MntWines             50000 non-null  int64
 10  MntFruits            50000 non-null  int64
 11  MntMeatProducts      50000 non-null  int64
 12  MntFishProducts      50000 non-null  int64
 13  MntSweetProducts     50000 non-null  int64
 14  MntGoldProds         50000 non-null  int64
 15  NumDealsPurchases    50000 non-null  int64
 16  NumWebPurchases      50000 non-null  int64
 17  NumCatalogPurchases  50000 non-null  int64
 18  NumStorePurchases    50000 non-null  int64
 19  NumWebVisitsMonth    50000 non-null  int64
 20  AcceptedCmp3         50000 non-null  int64
 21  AcceptedCmp4         50000 non-null  int64
 22  AcceptedCmp5         50000 non-null  int64
 23  AcceptedCmp1         50000 non-null  int64
 24  AcceptedCmp2         50000 non-null  int64
 25  Complain             50000 non-null  int64
 26  Z_CostContact        50000 non-null  int64
 27  Z_Revenue            50000 non-null  int64
 28  Response             50000 non-null  int64
dtypes: float64(1), int64(25), str(3)
memory usage: 11.1 MB

In [10]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Income"].fillna(df["Income"].median(), inplace=True)

C:\Users\sanje\AppData\Local\Temp\ipykernel_18592\2383243780.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Income"].fillna(df["Income"].median(), inplace=True)

0        58138.000000
1        46344.000000
2        71613.000000
3        26646.000000
4        58293.000000
             ...
49995    31197.365775
49996    77798.873393
49997    75403.247370
49998    95899.380617
49999    57724.469796
Name: Income, Length: 50000, dtype: float64

In [13]:
df["Income"].isnull().sum()

np.int64(24)

In [14]:
df["Income"] = df["Income"].fillna(df["Income"].median())

In [15]:
df["Income"].isnull().sum()

np.int64(0)

In [16]:
print("Education values:")
print(df["Education"].value_counts())

print("\nMarital Status values:")
print(df["Marital_Status"].value_counts())

Education values:
Education
Graduation    25162
PhD           10800
Master         8351
2n Cycle       4507
Basic          1180
Name: count, dtype: int64

Marital Status values:
Marital_Status
Married     19546
Together    12779
Single      10611
Divorced     5187
Widow        1728
Alone          68
Absurd         42
YOLO           39
Name: count, dtype: int64

In [17]:
df["Marital_Status"] = df["Marital_Status"].replace({
    "Alone": "Single",
    "Absurd": "Single",
    "YOLO": "Single"
})

In [18]:
df["Marital_Status"].value_counts()

Marital_Status
Married     19546
Together    12779
Single      10760
Divorced     5187
Widow        1728
Name: count, dtype: int64

In [19]:
print("Minimum Year of Birth:", df["Year_Birth"].min())
print("Maximum Year of Birth:", df["Year_Birth"].max())

Minimum Year of Birth: 1893
Maximum Year of Birth: 1996

In [20]:
df["Year_Birth"].value_counts().sort_index().head(10)

Year_Birth
1893      1
1899      1
1900      1
1940     86
1941     25
1943    142
1944    153
1945    173
1946    339
1947    352
Name: count, dtype: int64

In [21]:
df["Year_Birth"].value_counts().sort_index().tail(10)

Year_Birth
1987    642
1988    629
1989    634
1990    435
1991    325
1992    294
1993    120
1994     63
1995    112
1996     51
Name: count, dtype: int64

In [22]:
print("Invalid Year_Birth values:", (df["Year_Birth"] < 1940).sum())

Invalid Year_Birth values: 3

In [23]:
df[df["Year_Birth"] < 1940][["ID", "Year_Birth", "Income"]]

        ID  Year_Birth   Income
192   7829        1900  36640.0
239  11004        1893  60182.0
339   1150        1899  83532.0

In [24]:
df = df[df["Year_Birth"] >= 1940].copy()

In [25]:
print("Rows after removing invalid birth years:", len(df))
print("Invalid birth years remaining:", (df["Year_Birth"] < 1940).sum())

Rows after removing invalid birth years: 49997
Invalid birth years remaining: 0

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df["Education"] = df["Education"].replace({
    "2n Cycle": "2nd Cycle"
})

In [28]:
df["Education"].value_counts()

Education
Graduation    25162
PhD           10799
Master         8351
2nd Cycle      4505
Basic          1180
Name: count, dtype: int64

In [29]:
print("Income statistics:")
print(df["Income"].describe())

print("\nIncome outliers:")
Q1 = df["Income"].quantile(0.25)
Q3 = df["Income"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[(df["Income"] < lower_bound) | (df["Income"] > upper_bound)]

print("Number of income outliers:", len(outliers))

Income statistics:
count     49997.000000
mean      52428.724127
std       25928.726937
min        1641.049500
25%       35469.909988
50%       51615.901476
75%       68355.126592
max      721309.167447
Name: Income, dtype: float64

Income outliers:
Lower bound: -13857.914919376119
Upper bound: 117682.95149920518
Number of income outliers: 210

In [30]:
print("Income statistics:")
print(df["Income"].describe())

print("\nIncome outliers:")
Q1 = df["Income"].quantile(0.25)
Q3 = df["Income"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[(df["Income"] < lower_bound) | (df["Income"] > upper_bound)]

print("Number of income outliers:", len(outliers))

Income statistics:
count     49997.000000
mean      52428.724127
std       25928.726937
min        1641.049500
25%       35469.909988
50%       51615.901476
75%       68355.126592
max      721309.167447
Name: Income, dtype: float64

Income outliers:
Lower bound: -13857.914919376119
Upper bound: 117682.95149920518
Number of income outliers: 210

In [31]:
df["Income"] = df["Income"].clip(upper=upper_bound)

print("Maximum Income after capping:", df["Income"].max())

Maximum Income after capping: 117682.95149920518

In [32]:
print("Income outliers after capping:",
      ((df["Income"] < lower_bound) | (df["Income"] > upper_bound)).sum())

Income outliers after capping: 0

In [33]:
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    errors="coerce",
    dayfirst=True
)

print("Invalid dates:", df["Dt_Customer"].isnull().sum())

Invalid dates: 0

In [34]:
print(df["Dt_Customer"].min())
print(df["Dt_Customer"].max())

2012-07-30 00:00:00
2014-06-29 00:00:00

In [35]:
print("Response values:")
print(df["Response"].value_counts())

Response values:
Response
0    42603
1     7394
Name: count, dtype: int64

In [36]:
print("Missing Response values:", df["Response"].isnull().sum())

Missing Response values: 0

In [37]:
campaign_cols = [
    "AcceptedCmp1",
    "AcceptedCmp2",
    "AcceptedCmp3",
    "AcceptedCmp4",
    "AcceptedCmp5"
]

for col in campaign_cols:
    print(f"{col}:")
    print(df[col].value_counts())
    print()

AcceptedCmp1:
AcceptedCmp1
0    46806
1     3191
Name: count, dtype: int64

AcceptedCmp2:
AcceptedCmp2
0    49323
1      674
Name: count, dtype: int64

AcceptedCmp3:
AcceptedCmp3
0    46413
1     3584
Name: count, dtype: int64

AcceptedCmp4:
AcceptedCmp4
0    46252
1     3745
Name: count, dtype: int64

AcceptedCmp5:
AcceptedCmp5
0    46412
1     3585
Name: count, dtype: int64

In [38]:
print("Complain values:")
print(df["Complain"].value_counts())

Complain values:
Complain
0    49534
1      463
Name: count, dtype: int64

In [39]:
print("Unique values in Z_CostContact:", df["Z_CostContact"].nunique())
print("Unique values in Z_Revenue:", df["Z_Revenue"].nunique())

print("\nZ_CostContact values:")
print(df["Z_CostContact"].value_counts())

print("\nZ_Revenue values:")
print(df["Z_Revenue"].value_counts())

Unique values in Z_CostContact: 1
Unique values in Z_Revenue: 1

Z_CostContact values:
Z_CostContact
3    49997
Name: count, dtype: int64

Z_Revenue values:
Z_Revenue
11    49997
Name: count, dtype: int64

In [40]:
df.drop(columns=["Z_CostContact", "Z_Revenue"], inplace=True)

# Check remaining columns
print("Columns after removing constant columns:")
print(df.columns.tolist())

print("\nDataset shape:")
print(df.shape)

Columns after removing constant columns:
['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Response']

Dataset shape:
(49997, 27)

In [41]:
print("Number of unique IDs:", df["ID"].nunique())
print("Number of rows:", len(df))

print("\nDuplicate IDs:", df["ID"].duplicated().sum())
print("\nMissing IDs:", df["ID"].isnull().sum())

Number of unique IDs: 49997
Number of rows: 49997

Duplicate IDs: 0

Missing IDs: 0

In [41]:
print("Original ID retained.")
print("Number of unique IDs:", df["ID"].nunique())

Original ID retained.
Number of unique IDs: 49997

In [43]:
print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nTotal missing values:", df.isnull().sum().sum())

Dataset shape: (49997, 27)

Missing values:
Series([], dtype: int64)

Duplicate rows: 0

Data types:
ID                              int64
Year_Birth                      int64
Education                         str
Marital_Status                    str
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[us]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Response                        int64
dtype: object

Total missing values: 0

In [45]:
output_path = "../data/processed/customer_cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
Rows: 49997
Columns: 27